Description: >
    This template deploys a RDS instance.

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    VPC:
        Description: Choose which VPC this database should be deployed to
        Type: AWS::EC2::VPC::Id

    PrivateSubnets:
        Description: Subnets the RDS should be deployed to
        Type: List<AWS::EC2::Subnet::Id>

    VpcCIDR:
      Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
      Type: String

    DBUser:
        Description: The database admin account username
        Type: String

    DBPassword:
        Description: The database admin account password
        Type: String

    EC2SecurityGroup:
        Description: Select the Security Group to use for Game Server
        Type: AWS::EC2::SecurityGroup::Id

Resources:

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: RDS DB subnet group
      SubnetIds: !Ref PrivateSubnets

  DBEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Open database for access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '3306'
        ToPort: '3306'
        SourceSecurityGroupId: !Ref EC2SecurityGroup

  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: gamedb
      AllocatedStorage: 5
      DBInstanceClass: db.t2.micro
      Engine: MySQL
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups: [ !Ref DBEC2SecurityGroup ]
      MultiAZ: false
      Tags:
      - Key: Name
        Value: MySQL Database

Outputs:

    DBEndpoint:
        Description: A reference to the Database Endpoint
        Value: !GetAtt [Database, Endpoint.Address]

    DBEC2SecurityGroup:
        Description: A reference to the security group for RDS
        Value: !Ref DBEC2SecurityGroup
