Description: >
    This template deploys a RDS instance.

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    #VPC:
    #    Type: AWS::EC2::VPC::Id
    #    Description: Choose which VPC the Applicaion Load Balancer should be deployed to

    PrivateSubnet:
        Description: Choose which subnets the RDS should be deployed to
        Type: AWS::EC2::Subnet::Id

    DBSecurityGroup:
        Description: Select the Security Group to apply to the RDS
        Type: AWS::EC2::SecurityGroup::Id

    DBUser:
        Description: The database admin account username
        Type: String

    DBPassword:
        Description: The database admin account password
        Type: String

Resources:

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: RDS DB subnet group
      SubnetIds: !Ref PrivateSubnet

  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: gamedb
      AllocatedStorage: 5
      DBInstanceClass: db.t2.micro
      Engine: MySQL
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups: [ !Ref DBSecurityGroup ]
      DeletionPolicy: Snapshot
      MultiAZ: false
      Tags:
      - Key: Name
        Value: MySQL Database


Outputs:

    RDS:
        Description: A reference to the Application Load Balancer
        Value: !GetAtt [Database, Endpoint.Address]
