Description: >
    This template contains the security groups required by our entire stack.
    We create them in a seperate nested template, so they can be referenced
    by all of the other nested templates.
Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    VPC:
        Type: AWS::EC2::VPC::Id
        Description: Choose which VPC the security groups should be deployed to

Resources:

    # This security group defines who/where is allowed to access the ECS hosts directly.
    # By default we're just allowing access from the load balancer.  If you want to SSH
    # into the hosts, or expose non-load balanced services you can open their ports here.
    EC2SecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            VpcId: !Ref VPC
            GroupDescription: Access to the EC2 that run on them
            SecurityGroupIngress:
                # Only allow inbound access to ECS from the ELB
                - CidrIp: 0.0.0.0/0
                  IpProtocol: tcp
                  ToPort: 22
                  FromPort: 22
            Tags:
                - Key: Name
                  Value: !Sub ${EnvironmentName}-EC2

Outputs:

    EC2SecurityGroup:
        Description: A reference to the security group for EC2
        Value: !Ref EC2SecurityGroup
