Description: >

    This template deploys a VPC, with a pair of public and private subnets, and
    a game server and a database (MySQL) for Game Analytics Hands On.

    Last Modified: Sep 15, 2017
    Author: Hideyo Yoshida <hideyy@amazon.co.jp>

Parameters:

  KeyName:
    Description: EC2 key pair name for bastion host SSH access
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: Key pair name can contain only ASCII characters.

  DBUser:
    Description: The database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.

  DBPassword:
    NoEcho: 'true'
    Description: The database admin account password
    Type: String
    MinLength: '1'
    MaxLength: '41'
    ConstraintDescription: must contain only alphanumeric characters.


Resources:

    VPC:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/game-analytics-handson-jp/infrastructure/vpc.yaml
            Parameters:
                EnvironmentName:    !Ref AWS::StackName
                VpcCIDR:            10.180.0.0/16
                PublicSubnet1CIDR:  10.180.1.0/24
                PublicSubnet2CIDR:  10.180.2.0/24
                PrivateSubnet1CIDR: 10.180.11.0/24
                PrivateSubnet2CIDR: 10.180.12.0/24

    SecurityGroups:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/game-analytics-handson-jp/infrastructure/security-groups.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                VPC: !GetAtt VPC.Outputs.VPC

    EC2Instance:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/game-analytics-handson-jp/infrastructure/ec2.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                InstanceType: t2.micro
                VPC: !GetAtt VPC.Outputs.VPC
                PublicSubnet1: !GetAtt VPC.Outputs.PublicSubnet1
                EC2SecurityGroup: !GetAtt SecurityGroups.Outputs.EC2SecurityGroup
                KeyName: !Ref KeyName

    Database:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/game-analytics-handson-jp/infrastructure/rds.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                VPC: !GetAtt VPC.Outputs.VPC
                EC2SecurityGroup: !GetAtt SecurityGroups.Outputs.EC2SecurityGroup
                PrivateSubnets: !GetAtt VPC.Outputs.PrivateSubnets
                DBUser: !Ref DBUser
                DBPassword: !Ref DBPassword

Outputs:

  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !GetAtt EC2Instance.Outputs.InstanceId

  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt EC2Instance.Outputs.PublicDNS

  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt EC2Instance.Outputs.PublicIP

  DBEndpoint:
    Description: A reference to the Database Endpoint
    Value: !GetAtt Database.Outputs.DBEndpoint
